{% set version = "1.8.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-waveslim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/waveslim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/waveslim/waveslim_{{ version }}.tar.gz
  sha256: 408eeea72a218ef3458f0934ff556733cacf1a63ddaa52491abcc1fce6ed2094

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('waveslim')"           # [not win]
    - "\"%R%\" -e \"library('waveslim')\""  # [win]

about:
  home: http://waveslim.blogspot.com, http://www2.imperial.ac.uk/~bwhitche/book
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Basic wavelet routines for time series (1D), image (2D)  and array (3D) analysis.  The code provided here is based on wavelet methodology developed in Percival and Walden (2000); Gencay, Selcuk and Whitcher (2001); the dual-tree complex wavelet transform (DTCWT) from Kingsbury (1999, 2001) as implemented by Selesnick;
    and Hilbert wavelet pairs (Selesnick 2001, 2002).  All figures in chapters 4-7 of GSW (2001) are reproducible using this  package and R code available at the book website(s) below.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r


# Package: waveslim
# Version: 1.7.5.1
# Date: 2014-12-21
# Title: Basic Wavelet Routines for One-, Two- And Three-Dimensional Signal Processing
# Author: Brandon Whitcher
# Maintainer: Brandon Whitcher <bwhitcher@gmail.com>
# Depends: R (>= 2.11.0), graphics, grDevices, stats, utils
# Suggests: fftw
# Description: Basic wavelet routines for time series (1D), image (2D)  and array (3D) analysis.  The code provided here is based on wavelet methodology developed in Percival and Walden (2000); Gencay, Selcuk and Whitcher (2001); the dual-tree complex wavelet transform (DTCWT) from Kingsbury (1999, 2001) as implemented by Selesnick; and Hilbert wavelet pairs (Selesnick 2001, 2002).  All figures in chapters 4-7 of GSW (2001) are reproducible using this  package and R code available at the book website(s) below.
# License: BSD_3_clause + file LICENSE
# URL: http://waveslim.blogspot.com, http://www2.imperial.ac.uk/~bwhitche/book
# NeedsCompilation: yes
# Packaged: 2019-01-26 16:15:41 UTC; hornik
# Repository: CRAN
# Date/Publication: 2019-01-26 16:48:57 UTC
