travis:
  secure:
    BINSTAR_TOKEN: cyz/h3fCGX5Jg+Cfwb2Y/JANGPW0SfUFBBfRK9s5ciPwcyBKLVlEmC1KB0lq7TXqJPTRg9X1QoZzsFeffReVyK9Xle2DuWHPMHDJP/46RZCE7CCSCepM7o10BxncQXjJO8DnyTZHef6WIXIrx7hAIA11XgDAgkWHZLJLkJ6iGzFP3gm35gelFP3RWVxegE7IO26DW7Q3yAN1j83cwzxfXborXR2dk1oIvJc9kdzwYwn9M+OwltMebGylnSdRIQcAfIX5DOAtWDBafvK5FIgTXvtIFH+suqGVKTQqcSEYs3jroCvEO2cThdjA3IvqaBzUx2OftxpcH061orOrIdD9s38cqRoTZgJy+2SAMHkzLGl79KMd8rY+g0cJJzjhohGj736qezUefMt6FV7lXe9ObnCPfJlrzkFEOyeBrh6kyrSdHjrCCgOFpulKrvusXyR+dW7a/DaTbDQ42MTj3fS/Mv0QW+8HGzTeJbgOfeTKJXDgoJJjVWlRJpmvJZLhO0BGwrIzhKwTQoQ0ATvxd0W+6t6mGvyT8fs/y+P6ILL0nm0tzKOCOkZsWQdzOgoeG5qyQ5X5Qw7YG0xC/NLKqzcMf3e4Ut9//wA3txbXqRbkvzqXzn8+NUEoxlyJ3xchL2d7E5HKCNULGr2ji6/Fi5tfJ2xUy0wCmfVxtKsCJdWElog=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
