appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: l30Ie/nwS+AKiHSb5S53T6w57dJny+Zf/oGyMsSUunOc6YY9Kt1UlbdNHjSF3urLM+z+tzeiNm4jbr32KVW7fVJUFq6dS0makNZUs5/bMUP9eXtqcVU3vlh2FuiSUM2aHdCRYaJMSlooDia3PepMFqgHp/4vj7rzpaSc+tZ27VU492la/X6wZ4EJ9+AlvYY/ESF6ayoCa/saYXGk20fgh4EkCCmer8LGfueHoXB3ohl9vuNCuXpycnLFFNsg1cK9hVV56W+IjrdOZ7a+4+4kvUebSWeYPVNUhztRui84IsuptuGRJnh8IxPsOyy8yFMTTjmS+ZZgbEGAxZH9CNAsxqd8R+/opoCjTNoW4GjhRMziCU3V0mAAvLoRCZo564ZKf7VElONIYRh1Y5bbJc8q7Bf1JfkW1FHWJmRUh+rRnw8Fz/PqjouBY4b1qTEyVLpfNYguF4VvNl9s3ltFwPTmUrt4PHgo10PHY5TZubfzxKTxpqqGRiMlw/m/Y3PQjdB1dr97OaZf27hQMblYZ/+iPvzfwNZftU+HMwy42fka+eDBJV/OcMkeCj3SBvBFGNxtcv6cU3bQw3IS8owXcXQSV5IuN9rs2wU8ul9/R+WfjxR1hlGbMpXu/tW/bR5fOF2htLFPIN9XU4D3g2EPesbc7KjGC6seUCeL9zClJHC8/Z8=}
